### ISSUE TITLE
Failed at making Qubes Components during archlinux-minimal templateVM building

### ISSUE THREAD

**Issue by shenanegan** [Qubes-Community/Contents#138]
I strictly followed everything instructed [here](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md) but step ***5. Make all the require Qubes components*** won't work.

More specifically, errors start occurring when building qubes components by executing `make qubes-vm`. Everything before that works fine. But I can't get past that step.

Here is what I get after executing `make qubes-vm`:

```
Currently installed dependencies:
createrepo_c-0.17.1-1.fc32.x86_64
createrepo_c-0.17.1-1.fc32.x86_64
debootstrap-1.0.123-1.fc32.noarch
dialog-1.3-24.20191210.fc32.x86_64
dpkg-dev-1.20.7.1-2.fc32.noarch
git-2.26.3-2.fc32.x86_64
perl-Digest-MD5-2.58-1.fc32.x86_64
perl-Digest-SHA-6.02-442.fc32.x86_64
python3-sh-1.13.1-1.fc32.noarch
rpm-build-4.15.1.1-1.fc32.1.x86_64
rpmdevtools-8.10-10.fc32.noarch
--> Archlinux dist-prepare-chroot (makefile):
  --> Checking mounting of dev/proc/sys on build chroot...
mknod: ./test-dev-null: File exists
mknod: ./test-dev-null: File exists
*******************************************************************************
***                               ERROR                                      ***
*** Cannot create chroot because the current filesystem is mounted as nodev. ***
*** Build Qubes on a different filesystem, or run 'make remount' to remount  ***
*** /home with dev option.
***                                                                          ***
*******************************************************************************
make[1]: *** [Makefile.generic:153: generic-prepare-chroot] Error 1
make: *** [Makefile:259: core-vchan-xen-vm] Error 1
--> Archlinux dist-prepare-chroot (makefile):
make: *** Waiting for unfinished jobs....
  --> Checking mounting of dev/proc/sys on build chroot...
*******************************************************************************
***                               ERROR                                      ***
*** Cannot create chroot because the current filesystem is mounted as nodev. ***
*** Build Qubes on a different filesystem, or run 'make remount' to remount  ***
*** /home with dev option.
***                                                                          ***
*******************************************************************************
make[1]: *** [Makefile.generic:153: generic-prepare-chroot] Error 1
make[1]: *** Waiting for unfinished jobs....
-> Building core-qubesdb (archlinux) for archlinux vm (logfile: build-logs/core-qubesdb-vm-archlinux.log)
  --> Synchronize resolv.conf, in case it changed since last run...
  --> Synchronize resolv.conf, in case it changed since last run...
make: *** [Makefile:259: vmm-xen-vm] Error 1
--> build failed!
--> Archlinux dist-build-dep (makefile)
make[2]: *** read jobs pipe: Bad file descriptor.  Stop.
make[2]: *** Waiting for unfinished jobs....
  --> Generate locales...
en_US.UTF-8 UTF-8
Generating locales...
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.UTF-8... done
Generation complete.
LANG=en_US.UTF-8
-> Archlinux update-local-repo.sh
ls: cannot access '*.sig': No such file or directory
ls: cannot access 'pkgs/*.pkg.tar.*': No such file or directory
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
 qubes downloading...
warning: archlinux-keyring-20210616-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) archlinux-keyring-20210616-1

Total Installed Size:  1.32 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
reinstalling archlinux-keyring...
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
==> Importing owner trust values...
==> Disabling revoked keys in keyring...
==> Updating trust database...
gpg: next trustdb check due at 2021-08-02
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
 qubes downloading...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) sqlite-3.36.0-1

Total Download Size:   1.70 MiB
Total Installed Size:  9.50 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 sqlite-3.36.0-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
upgrading sqlite...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:259: core-qubesdb-vm] Error 1
```

**Comment by neowutran** [comment]
Can you double check if you executed the "make remount" command ? 
This specific command should fix this specific error

**Comment by shenanegan** [comment]
Sorry for answering this late, I didn't have time to try it again. I tried for a third time, making sure to execute the `make remount` command and it still throws the error.

**Comment by CtrlC-Root** [comment]
By the way, I ran into the same error about the `/home` filesystem not being mounted with `dev`, and I found that not setting the Make flags in `/etc/profile.d/99-makeflags.sh` fixes it. I think there may be a race condition somewhere in the build steps that you run into when using more than one core. Of course it still fails later on in the process but for a different reason.

**Comment by lubellier** [comment]
Hi @shenanegan ,
  I [updated](https://github.com/Qubes-Community/Contents/pull/141) the [ArchLinux build guide](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md) and built the 4.1 packages without issue.
  With the [known-issues](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md#known-issues) section and the @CtrlC-Root above comment, please could you try again?

**Comment by awokd** [comment]
Pls reopen if this is still an issue.

**Comment by tristandruyen** [comment]
I can confirm this issue still occurs.
Worked after removing the 99-makeflags.sh

**Comment by awokd** [comment]
> I can confirm this issue still occurs. Worked after removing the 99-makeflags.sh

Are the steps you had to take different than the following?

https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md#1-open-a-non-root--terminal-in-the-fedora-33-minimal-templatevm
